apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
        app.kubernetes.io/name: demo-app
      name: demo-app
    spec:
      containers:
      - name: demo-app
        image: registry.local/demo-app:5
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
      imagePullSecrets:
      - name: registry-tls
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app.kubernetes.io/name: demo-app
spec:
  selector:
    app.kubernetes.io/name: demo-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
