apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-sm
  namespace: monitoring
  labels:
    release: prom-stack
spec:
  namespaceSelector:
    matchNames: ["default"]
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
